using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Platform.Application.Scanning.Contracts;

namespace Platform.Application.Scanning.Adapters;

/// <summary>
/// Execution plan generated by a tool adapter for the ScannerRuntimeSandbox.
/// </summary>
public sealed record ToolExecutionPlan(
    string ToolKey,
    string Version,
    IReadOnlyList<string> CommandLineArguments,
    IReadOnlyDictionary<string, string> EnvironmentVariables,
    string? TargetInputFilePath = null,
    string? TargetInputContent = null,
    IReadOnlyDictionary<string, string>? AdditionalMetadata = null,
    IReadOnlyList<string>? AllowedVerificationDestinations = null
);

/// <summary>
/// Parsed raw output produced by a tool adapter parser.
/// </summary>
public sealed record ToolParsedOutputResult(
    string ToolKey,
    string Version,
    IReadOnlyList<FindingCandidate> FindingCandidates,
    ScannerCoverage? Coverage,
    string? ParseFailureReason = null
);

/// <summary>
/// Universal scanner tool adapter interface (SPEC-008).
/// Pure capability translator: transforms target context into execution plans and parses raw outputs into finding candidates.
/// </summary>
public interface IScanToolAdapter
{
    /// <summary>Immutable supply chain manifest of the scanner tool.</summary>
    ScanToolManifest Manifest { get; }

    /// <summary>Prepares sandbox execution arguments and environment variables.</summary>
    ToolExecutionPlan PrepareExecution(ScanExecutionContext context);

    /// <summary>Parses raw stdout/stderr into normalized finding candidates and bounded coverage.</summary>
    Task<ToolParsedOutputResult> ParseOutputAsync(
        ScanExecutionContext context,
        ToolExecutionRawOutput rawOutput,
        CancellationToken ct = default);
}
