// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Infrastructure.Persistence;

#nullable disable

namespace Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260812113705_AddPhase3Tables")]
    partial class AddPhase3Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Domain.Entities.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckpointFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QueuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkerInstanceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatAtUtc");

                    b.HasIndex("QueuedByUserId");

                    b.HasIndex("Status", "Priority", "QueuedAtUtc");

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.ApiHunterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountTier")
                        .HasColumnType("text");

                    b.Property<string>("ApiType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AwsAccountId")
                        .HasColumnType("text");

                    b.Property<string>("AwsRiskLevel")
                        .HasColumnType("text");

                    b.Property<string>("Balance")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstFoundUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFoundUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SourceRecordId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationResponse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceRecordId")
                        .IsUnique();

                    b.HasIndex("Status", "ApiType");

                    b.ToTable("api_hunter_records", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.ApiHunterRepoReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiHunterRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeContext")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SourceReferenceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApiHunterRecordId");

                    b.HasIndex("SourceReferenceId")
                        .IsUnique();

                    b.HasIndex("RepoOwner", "RepoName");

                    b.ToTable("api_hunter_repo_references", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.ApiHunterSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastSyncedKeyId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordsImported")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("api_hunter_sync_states", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("authentication_sessions", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.CandidateOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectionRuleId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LineContentRawEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("LineContentRedacted")
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MatchLength")
                        .HasColumnType("integer");

                    b.Property<int>("MatchStartIndex")
                        .HasColumnType("integer");

                    b.Property<string>("OccurrenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("SnapshotFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("OccurrenceFingerprint")
                        .IsUnique();

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SnapshotFileId");

                    b.HasIndex("DetectionRuleId", "RuleVersion");

                    b.ToTable("candidate_occurrences", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.CredentialCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EncryptedRawValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FingerprintKeyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstDetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastDetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecretFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalOccurrences")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CredentialType");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("SecretFingerprint")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("credential_candidates", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.DetectionRule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("AllowlistPatternsJson")
                        .HasColumnType("text");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RegexPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "Version");

                    b.ToTable("detection_rules", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.FieldPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("PermissionCode", "ResourceType", "FieldName", "Action")
                        .IsUnique();

                    b.ToTable("field_permissions", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.NotificationProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("notification_provider_configs", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcquisitionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ProviderRepoId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcquisitionStatus");

                    b.HasIndex("Owner", "Name");

                    b.HasIndex("Provider", "ProviderRepoId")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.RepositorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AnalysisCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ArchiveObjectKey")
                        .HasColumnType("text");

                    b.Property<long>("ArchiveSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CandidatesFound")
                        .HasColumnType("integer");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AcquiredAtUtc");

                    b.HasIndex("AnalysisStatus");

                    b.HasIndex("RepositoryId", "CommitSha")
                        .IsUnique();

                    b.ToTable("repository_snapshots", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.RepositorySource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiHunterRecordId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ApiHunterRepoRefId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscoveredViaQuery")
                        .HasColumnType("text");

                    b.Property<string>("DiscoveryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApiHunterRecordId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RepositoryId", "ApiHunterRecordId", "ApiHunterRepoRefId")
                        .IsUnique();

                    b.ToTable("repository_sources", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.SnapshotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBinary")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("SnapshotId");

                    b.ToTable("snapshot_files", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Entities.AnalysisJob", b =>
                {
                    b.HasOne("Platform.Domain.Entities.User", "QueuedByUser")
                        .WithMany()
                        .HasForeignKey("QueuedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QueuedByUser");
                });

            modelBuilder.Entity("Platform.Domain.Entities.ApiHunterRepoReference", b =>
                {
                    b.HasOne("Platform.Domain.Entities.ApiHunterRecord", "ApiHunterRecord")
                        .WithMany("RepoReferences")
                        .HasForeignKey("ApiHunterRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiHunterRecord");
                });

            modelBuilder.Entity("Platform.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("Platform.Domain.Entities.User", "User")
                        .WithMany("AuditEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Entities.AuthenticationSession", b =>
                {
                    b.HasOne("Platform.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Entities.CandidateOccurrence", b =>
                {
                    b.HasOne("Platform.Domain.Entities.CredentialCandidate", "Candidate")
                        .WithMany("Occurrences")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Domain.Entities.Repository", "Repository")
                        .WithMany("Occurrences")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Domain.Entities.SnapshotFile", "SnapshotFile")
                        .WithMany("Occurrences")
                        .HasForeignKey("SnapshotFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Domain.Entities.DetectionRule", "DetectionRule")
                        .WithMany("Occurrences")
                        .HasForeignKey("DetectionRuleId", "RuleVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("DetectionRule");

                    b.Navigation("Repository");

                    b.Navigation("SnapshotFile");
                });

            modelBuilder.Entity("Platform.Domain.Entities.CredentialCandidate", b =>
                {
                    b.HasOne("Platform.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("Platform.Domain.Entities.FieldPermission", b =>
                {
                    b.HasOne("Platform.Domain.Entities.Permission", "Permission")
                        .WithMany("FieldPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Platform.Domain.Entities.RepositorySnapshot", b =>
                {
                    b.HasOne("Platform.Domain.Entities.Repository", "Repository")
                        .WithMany("Snapshots")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Platform.Domain.Entities.RepositorySource", b =>
                {
                    b.HasOne("Platform.Domain.Entities.ApiHunterRecord", "ApiHunterRecord")
                        .WithMany()
                        .HasForeignKey("ApiHunterRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Platform.Domain.Entities.Repository", "Repository")
                        .WithMany("Sources")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiHunterRecord");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Platform.Domain.Entities.SnapshotFile", b =>
                {
                    b.HasOne("Platform.Domain.Entities.RepositorySnapshot", "Snapshot")
                        .WithMany("Files")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Platform.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("Platform.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Entities.ApiHunterRecord", b =>
                {
                    b.Navigation("RepoReferences");
                });

            modelBuilder.Entity("Platform.Domain.Entities.CredentialCandidate", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("Platform.Domain.Entities.DetectionRule", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("Platform.Domain.Entities.Permission", b =>
                {
                    b.Navigation("FieldPermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Platform.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("Snapshots");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Platform.Domain.Entities.RepositorySnapshot", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Platform.Domain.Entities.SnapshotFile", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("Platform.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Sessions");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
